//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsPresentationFoundation.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WindowsPresentationFoundation.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shirt number:.
        /// </summary>
        public static string BrojDresa {
            get {
                return ResourceManager.GetString("BrojDresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goals conceded:.
        /// </summary>
        public static string BrojPrimljenihGolova {
            get {
                return ResourceManager.GetString("BrojPrimljenihGolova", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of games:.
        /// </summary>
        public static string BrojUtakmica {
            get {
                return ResourceManager.GetString("BrojUtakmica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goals:.
        /// </summary>
        public static string BrojZabijenihGolova {
            get {
                return ResourceManager.GetString("BrojZabijenihGolova", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yellow card:.
        /// </summary>
        public static string BrojZutihKartona {
            get {
                return ResourceManager.GetString("BrojZutihKartona", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fifa code:.
        /// </summary>
        public static string FifaCode {
            get {
                return ResourceManager.GetString("FifaCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player name:.
        /// </summary>
        public static string ImeIgraca {
            get {
                return ResourceManager.GetString("ImeIgraca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string Izadi {
            get {
                return ResourceManager.GetString("Izadi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select language:.
        /// </summary>
        public static string Jezik {
            get {
                return ResourceManager.GetString("Jezik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Captain:.
        /// </summary>
        public static string Kapetan {
            get {
                return ResourceManager.GetString("Kapetan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favourite team:.
        /// </summary>
        public static string NajdraziTim {
            get {
                return ResourceManager.GetString("NajdraziTim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country:.
        /// </summary>
        public static string NazivDrzave {
            get {
                return ResourceManager.GetString("NazivDrzave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draws:.
        /// </summary>
        public static string Neodluceno {
            get {
                return ResourceManager.GetString("Neodluceno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Victories:.
        /// </summary>
        public static string Pobjede {
            get {
                return ResourceManager.GetString("Pobjede", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defeat:.
        /// </summary>
        public static string Porazi {
            get {
                return ResourceManager.GetString("Porazi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Postavke {
            get {
                return ResourceManager.GetString("Postavke", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string Potvrdi {
            get {
                return ResourceManager.GetString("Potvrdi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position:.
        /// </summary>
        public static string Pozicija {
            get {
                return ResourceManager.GetString("Pozicija", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose championship:.
        /// </summary>
        public static string Prvenstvo {
            get {
                return ResourceManager.GetString("Prvenstvo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Difference:.
        /// </summary>
        public static string Razlika {
            get {
                return ResourceManager.GetString("Razlika", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select resolution.
        /// </summary>
        public static string Rezolucija {
            get {
                return ResourceManager.GetString("Rezolucija", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pitcure:.
        /// </summary>
        public static string Slika {
            get {
                return ResourceManager.GetString("Slika", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose opponent:.
        /// </summary>
        public static string Suparnik {
            get {
                return ResourceManager.GetString("Suparnik", resourceCulture);
            }
        }
    }
}
